server:
  port: 8080

spring:
  cloud:
    gcp:
      sql:
        instance-connection-name: ${DB_INSTANCE_CONNECTION_NAME}
        database-name: sbps_api
  datasource:
    url: jdbc:postgresql:///${spring.cloud.gcp.sql.database-name}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

device:
  url: ${DEVICE_URL:http://localhost:8081}

jwt:
  secret: ${JWT_SECRET}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

service-user:
  email: ${SERVICE_USER_EMAIL}
  password: ${SERVICE_USER_PASSWORD}

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:5173}